# Account [/account]

## Get user info [GET]

+ Response 401

+ Request
    + Headers

            Authorization: Bearer ABC123

+ Response 200
    + Body

            {
              "name": "John",
              "phone": "+38 (098) 123 45 67",
              "email": "user.email@gmail.com",
              "birthday": "15.01.1990",
              "gender": "m",
              "bonus": 11.50,
              "subscribed_on_newsletters": true,
              "delivery_places": [
                {
                  "name": "",
                  "address": "Street name, house number / apartment number",
                  "door_code": "",
                  "comment": ""
                }
              ],
              "orders": [
                {
                  "id": 1,
                  "created_at": "14.12.2018 14:20:15",
                  "name": "John",
                  "phone": "+38 (098) 123 45 67",
                  "email": "user.email@gmail.com",
                  "delivery_method": "courier",
                  "delivery_place_id": 1, 
                  "delivery_datetime": "15.12.2018 16:55",
                  "comment": ""
                }
              ],
              "credit_cards": [
                {
                  "id": 1,
                  "provider": "liqpay",
                  "number": "1234567890123456",
                  "expiration_date": "12/2021",
                  "cvv": "123",
                  "owner_name": "John Smith",
                  "position": 1
                }
              ],
              "favourite_product_ids": [1,2,3],
              "cart_entries": [
                {
                  "id": 1,
                  "product_id": 1,
                  "quantity": 2,
                  "available_quantity": 3
                }
              ]
            }