# Blog articles [/blog-articles]

# Get all articles [GET]

<!-- include(last_update_date_time.md) -->

+ Response 200
    + Body
            [
              {
                "id": 1,
                "release_date": "21.06.2018",
                "medium_image": "/photo/example.jpg",
                "large_image": "/photo/example.jpg",
                "small_image": "/photo/example.jpg",
                "translations": [
                  {
                    "locale": "uk",
                    "name": "Най-най-най…піца у світі. Три найкрутіших",
                    "description": "Світ так швидко рухається, усе змінюється, трансформується у щось нове. Горизонти розширюються, і усе менше речей нас дивує. Тож і кулінарна справа не стоїть на місці. Інновації торкнулись навіть старої доброї піци. Хоча, кому-кому, а піці покращення не потрібні. Вона ж ідеальна!",
                    "content": "<html code>"
                  }
                ]
              }
            ]
            