FORMAT: 1A

# Smaki-maki API

<!-- include(data_structures/base_types.apib) -->
<!-- include(data_structures/product.apib) -->

# Group Catalog
<!-- include(categories.apib) -->
<!-- include(products.apib) -->
<!-- include(promotions.apib) -->
<!-- include(ingredients.apib) -->

# Group Blog
<!-- include(blog_articles.apib) -->
# Group Static texts
<!-- include(static_texts.apib) -->
# Group Subscriptions
<!-- include(subscriptions.apib) -->

# Group User
<!-- include(users.apib) -->
<!-- include(authentication.apib) -->
<!-- include(account.apib) -->
<!-- include(cart.apib) -->
<!-- include(credit_cards.apib) -->
<!-- include(delivery_places.apib) -->
