# Static texts [/static-texts]

## Get static texts [GET]

+ Response 200
    + Body
            {
              "uk": {
                "delivery_page": {
                  "content": "<html code>"
                },
                "about_us_page": {
                  "content": "<html code>"
                }
              }
            }