# Data Structures
## Product (object)

+ id (integer) - id of product
+ subcategory_id (integer) - id of subcategory
+ translations (array) - array of translations
  + locale (string)
  + name (string)
  + description (string)
+ large_image (string) - URL of image without domain and protocol
+ small_image - URL of image without domain and protocol
+ ingredient_ids (array[integer]) - array of ids of product's ingredients
+ additional_ingredient_ids (array<integer>) - array of ids of product's additional ingredients
+ price (float) - price of product
+ weight (integer) - weight of product